#!/usr/bin/env ansible-playbook
# tested on Fedora 30 only
- hosts: localhost
  become: true
  tasks:
    - dnf: 
        name: 
          - rabbitmq-server
          - python3
          - python3-pika
        state: latest  
    - systemd:
        name: rabbitmq-server.service
        state: started
        enabled: yes

